FROM python:3.9
RUN mkdir /app
WORKDIR /app
RUN apt-get update && apt-get install -y vim && apt-get install -y pip

# docker build --tag seed-test:local .
# docker run -it -v $PWD:/app $(docker images seed-test -aq) bash
